### ISSUE TITLE
Update required?

### ISSUE THREAD

**Issue by ColinGilbert** [ruslo/weather#2]
Hi,

I notice that this was written a while ago, and the official documentation of Hunter says nothing about Sugar. Is that a completely different too from Hunter, or is it deprecated?

Thanks,
Colin

**Comment by ruslo** [comment]
> I notice that this was written a while ago

Yes, it's true. Have not such time to apply updates. Do you have any problems? It should work I think.

> and the official documentation of Hunter says nothing about Sugar

Sugar is a package, so you can find [pkg.sugar](https://github.com/ruslo/hunter/wiki/pkg.sugar) link which will lead to the documentation.

**Comment by ColinGilbert** [comment]
Hi,

After matching up all versions to latest, it seems to have brought me an error on gcc 4.9.3

```
sober/log/Severity.cpp:28:13: error: ‘runtime_error’ is not a member of ‘std’
       throw std::runtime_error("sober::log::Severity switch");
```

**Comment by ruslo** [comment]
Seems like fixed but not released: https://github.com/ruslo/sober/commit/10617830dd6a3fb79abd97af7b46bdc9ef4d33c0

**Comment by ruslo** [comment]
Fixed in `master`: https://github.com/ruslo/weather/commit/56eee62eaac327e1a048165aaa868c2f3a71972f
